[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/js/script.outbound-links.js"
  to = "https://plausible.io/js/script.outbound-links.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true
